/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useApp } from '../context/AppContext';
import { useBooking } from '../context/BookingContext';

export function useModels() {
  const {
    models,
    isLoadingModels,
    favorites,
    handleFavoriteToggle,
    activeHomeCategory,
    setActiveHomeCategory,
    searchLocation,
    setSearchLocation,
    searchCategory,
    setSearchCategory,
    searchGender,
    setSearchGender,
    searchAgeRange,
    setSearchAgeRange,
    searchHeightClass,
    setSearchHeightClass,
    searchExperience,
    setSearchExperience,
    searchBudgetLimit,
    setSearchBudgetLimit,
    searchOnlyVerified,
    setSearchOnlyVerified,
    searchAvailableOnly,
    setSearchAvailableOnly,
    searchRadius,
    setSearchRadius,
    projectCoords,
    setProjectCoords,
    projectName,
    setProjectName,
    sortBy,
    setSortBy,
    searchQuery,
    setSearchQuery,
    resetFilters,
    filteredModels,
    filterKey,
    recentSearches,
    saveSearchQuery,
    deleteRecentSearch,
    isMobileFiltersOpen,
    setIsMobileFiltersOpen,
    showEliteModal,
    setShowEliteModal,
    eliteModelForModal,
    setEliteModelForModal,
    handleOpenEliteModal
  } = useApp();

  const {
    handleModelRegisterSubmit,
    handleAdminBatchApproveModels,
    handleAdminApproveModel,
    handleAdminRejectModel
  } = useBooking();

  return {
    models,
    isLoadingModels,
    favorites,
    handleFavoriteToggle,
    activeHomeCategory,
    setActiveHomeCategory,
    searchLocation,
    setSearchLocation,
    searchCategory,
    setSearchCategory,
    searchGender,
    setSearchGender,
    searchAgeRange,
    setSearchAgeRange,
    searchHeightClass,
    setSearchHeightClass,
    searchExperience,
    setSearchExperience,
    searchBudgetLimit,
    setSearchBudgetLimit,
    searchOnlyVerified,
    setSearchOnlyVerified,
    searchAvailableOnly,
    setSearchAvailableOnly,
    searchRadius,
    setSearchRadius,
    projectCoords,
    setProjectCoords,
    projectName,
    setProjectName,
    sortBy,
    setSortBy,
    searchQuery,
    setSearchQuery,
    resetFilters,
    filteredModels,
    filterKey,
    recentSearches,
    saveSearchQuery,
    deleteRecentSearch,
    isMobileFiltersOpen,
    setIsMobileFiltersOpen,
    showEliteModal,
    setShowEliteModal,
    eliteModelForModal,
    setEliteModelForModal,
    handleOpenEliteModal,
    handleModelRegisterSubmit,
    handleAdminBatchApproveModels,
    handleAdminApproveModel,
    handleAdminRejectModel
  };
}
